import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :weather_app_2, WeatherApp2Web.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: WeatherApp2.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
# Configure your database
config :weather_app_2, WeatherApp2.Repo,
  maintenance_database: "defaultdb",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  ssl: true,
  pool_size: 10,
  ssl_opts: [
    cacertfile: "priv/cert/ca.pem"
  ]
